#!/bin/bash

#
# nhttpsnoop: snoop Node HTTP requests
#

function usage
{
        cat >&2 << USAGE
usage: $nhs_arg0 [-l] [-o col,...] [-p pid,...]

Trace Node.js HTTP server activity.  By default, all requests from all Node.js
servers on the system are traced, and each one is displayed as it completes.

Options:

    -l            Display two lines for each request: one when the request is
                  received, and one when the response is sent (instead of just
                  one line when the response is sent).  Note that these lines
                  may not be adjacent, since multiple requests may be received
                  before any responses are sent if the request handling is
                  asynchronous.

    -n            Don't actually run DTrace, but instead just print out the D
                  script that would be used.

    -o col,...    Display the specified columns instead of the default output.
                  Available columns include:

                latency time in microseconds between the request being received
                        and the response being sent.  With -l, this field is
                        blank for the line denoting the start of the request.
        
                method  Request's HTTP method
        
                path    Request's HTTP URL path (excludes query parameters)
        
                pid     process identifier
        
                raddr   Client's IPv4 address
        
                rport   Client's TCP port
        
                time    relative time of the event from when $nhs_arg0 started
        
                url     Request's full HTTP URL, including query parameters
        
    -p pid,...    Only trace the specified processes.

This tool uses the Node.js DTrace provider and dtrace(1M).  You must have
appropriate permissions to run it.
USAGE
	exit 2
}

function fail
{
	echo "$nhs_arg0: $*" >&2
	exit 1
}

#
# optsplit str
#
# Split a comma- or whitespace-separated string into its constituent pieces.
# This is used to split the -p option (typically something like "-p pid1 pid2")
# and the "-o" option (typically something like "-o col1,col2").
#
function optsplit
{
	for arg in "$@"; do
		IFS=,
		for carg in $arg; do
			echo $carg
		done
		IFS=
	done
}

#
# join sep arg1 ...
#
# Join the arguments (strings) with the given separator string.
#
function join
{
	local sep=$1
	shift

	echo -n "$1"
	shift

	for elt in "$@"; do
		echo -ne "$sep"
		echo -n "$elt"
	done
}

#
# emit_printf fmt arg1 ...
#
# Emit a DTrace "printf" statement.
#
function emit_printf
{
	local fmt="$1"
	shift

	echo -ne "\tprintf($fmt,\n\t    "
	join ",\n\t    " "$@"
	echo ");"
}

#
# emit_header
#
# Emit a header row for the currently selected columns.
#
function emit_header
{
	local fmts= args=
	for column in $nhs_cols; do
		case $column in
		fd)
			fmts="$fmts %4s"
			args="$args \"FD\""
			;;

		latency)
			fmts="$fmts %10s"
			args="$args \"LATENCY\""
			;;

		method)
			fmts="$fmts %-6s"
			args="$args \"METHOD\""
			;;

		path)
			fmts="$fmts %-20s"
			args="$args \"PATH\""
			;;

		pid)
			fmts="$fmts %6s"
			args="$args \"PID\""
			;;

		raddr)
			fmts="$fmts %-16s"
			args="$args \"RADDR\""
			;;

		rport)
			fmts="$fmts %5s"
			args="$args \"RPORT\""
			;;

		time)
			fmts="$fmts %-12s"
			args="$args \"TIME\""
			;;

		url)
			fmts="$fmts %-20s"
			args="$args \"URL\""
			;;

		which)
			fmts="$fmts %2s"
			args="$args \"\""
			;;

		esac
	done

	emit_printf "\"$(join " " $fmts)\\\\n\"" $args
}

#
# emit_row request|response conn method uri
#
# Emit the body of a DTrace clause that will print out the fields requested by
# the user.  Because the http-server-request and http-server-response probes
# access their arguments differently, the caller specifies how to access the
# connection object and the method and URI in the current context.
#
function emit_row
{
	local which=$1 conn=$2 method=$3 uri=$4
	local fmts=
	local args=
	local lat=

	for column in $nhs_cols; do
		case $column in
		fd)
			fmts="$fmts %4d"
			args="$args $conn->fd"
			;;

		latency)
			if [[ $which = "request" ]]; then
				fmts="$fmts %10s"
				args="$args \"-\""
			else
				fmts="$fmts %4d.%-03dms"
				lat="(timestamp-rqstarts[$conn->remoteAddress,$conn->remotePort])"
				args="$args $lat/MICROSEC"
				args="$args ($lat%MICROSEC)/1000"
			fi
			;;

		method)
			fmts="$fmts %-6s"
			args="$args $method"
			;;

		path)
			fmts="$fmts %-20s"
			args="$args strtok($uri,\"?\")"
			;;

		pid)
			fmts="$fmts %6d"
			args="$args pid"
			;;

		raddr)
			fmts="$fmts %-16s"
			args="$args $conn->remoteAddress"
			;;

		rport)
			fmts="$fmts %5d"
			args="$args $conn->remotePort"
			;;

		time)
			fmts="$fmts [%3d.%06d]"
			args="$args (timestamp-start)/NANOSEC"
			args="$args (timestamp-start)%MICROSEC"
			;;

		url)
			fmts="$fmts %-20s"
			args="$args $uri"
			;;

		which)
			if [[ $which = "request" ]]; then
				fmts="$fmts ->"
			else
				fmts="$fmts <-"
			fi
			;;

		*)
			fail "invalid column name: $column"
			;;
			
		esac
	done

	emit_printf "\"$(join " " $fmts)\\\\n\"" $args
}

nhs_arg0=$(basename $0)			# program name (for error messages)
nhs_tmpfile=/var/tmp/$nhs_arg0.$$.d	# dynamically-generated D script
nhs_pids=				# selected pids (-p)
nhs_cols=				# selected columns (-o)
nhs_dryrun="false"			# just print script and exit (-n)
nhs_tracestart="false"			# print "request" events (-l)

while getopts "lno:p:" c; do
	case $c in
	l)	nhs_tracestart="true"		;;
	n)	nhs_dryrun="true"		;;
	o)	nhs_cols=$(optsplit $OPTARG)	;;
	p)	nhs_pids=$(optsplit $OPTARG)	;;
	*)	usage
	esac
done

# Configure default columns.
if [[ -z "$nhs_cols" ]]; then
	if [[ $nhs_tracestart = "true" ]]; then
		nhs_cols="time pid which latency method path"
	else
		nhs_cols="time pid latency method path"
	fi
fi

cat > $nhs_tmpfile <<EOF
#!/usr/sbin/dtrace -Cs

#pragma D option quiet

#define MILLISEC (1000)
#define	MICROSEC (1000 * 1000)
#define	NANOSEC  (1000 * 1000 * 1000)

BEGIN
{
$(emit_header)
	start = timestamp;
}

node*:::http-server-request
EOF

#
# We generate the DTrace script dynamically based on the options given.  If -p
# was specified, we predicate our first probe on the given set of pids.
#
if [[ -n "$nhs_pids" ]]; then
	set -- $nhs_pids

	if [[ $# -eq 1 ]]; then
		echo "/pid == $1/" >> $nhs_tmpfile
	else
		echo "/pid == $1" >> $nhs_tmpfile
		shift
		for pid in "$@"; do
			echo " || pid == $pid" >> $nhs_tmpfile
		done
		echo "/" >> $nhs_tmpfile
	fi
fi

echo "{" >> $nhs_tmpfile

[[ $nhs_tracestart = "true" ]] && 
	emit_row "request" "args[1]" \
	    "args[0]->method" "args[0]->url" >> $nhs_tmpfile

cat >> $nhs_tmpfile <<EOF
	rqstarts[args[1]->remoteAddress, args[1]->remotePort] = timestamp;
	rqmethods[args[1]->remoteAddress, args[1]->remotePort] = args[0]->method;
	rqurls[args[1]->remoteAddress, args[1]->remotePort] = args[0]->url;
}

node*:::http-server-response
/rqstarts[args[0]->remoteAddress, args[0]->remotePort]/
{
$(emit_row "response" 'args[0]' \
    'rqmethods[args[0]->remoteAddress,args[0]->remotePort]' \
    'rqurls[args[0]->remoteAddress,args[0]->remotePort]')
	rqstarts[args[0]->remoteAddress, args[0]->remotePort] = 0;
	rqmethods[args[0]->remoteAddress, args[0]->remotePort] = 0;
	rqurls[args[0]->remoteAddress, args[0]->remotePort] = 0;
}
EOF

if [[ $nhs_dryrun = "true" ]]; then
	cat $nhs_tmpfile
	rm -f $nhs_tmpfile
	exit 0
fi

chmod +x $nhs_tmpfile
dtrace $DTRACE_OPTS -Cs $nhs_tmpfile || \
    echo "$nhs_arg0: failed to invoke dtrace(1M)" >&2
rv=$?
rm -f $nhs_tmpfile
exit $rv
